spring.application.name=OlhoNoBoleto

spring.datasource.url=${DATABASE_URL}?useSSL=true&requireSSL=true&verifyServerCertificate=false&allowPublicKeyRetrieval=true&connectTimeout=5000&socketTimeout=10000&serverTimezone=UTC
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.main.lazy-initialization=true
spring.main.web-application-type=servlet
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Health check mínimo
management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.initialization-fail-timeout=0

# Porta
server.port=10000